function instructionsKeyMapping(p,wait)

%% Written Instructions
if p.session.isGamified
    instructions(p,['In the game, you will press keys corresponding to the color you see on the screen.\n\n',...
        'In this practice you will see a row of Xs appear on the screen in different ink colors. ',...
        'You should press the key that corresponds to the color of the Xs.\n\n',...
        'After each response, you will be told whether you were correct or incorrect.\n\n',...
        'Please do your best to make sure you learn which key corresponds to which ink color.',...
        ],wait);
    
else
    instructions(p,['In this practice, a row of Xs will appear on the screen in different ink colors. \n\n',...
        'Press the key that corresponds to the color of the Xs. \n\n',...
        'After each response, you will be told whether you \nwere correct or incorrect. \n\n',...
        'Please do your best to make sure you learn which key corresponds to which ink color.',...
        ],wait);
end

keyMappingReminder(p);

end